apiVersion: v1
kind: Service
metadata:
  name: mani-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: mani
  ports:
    - name: travel
      port: 4001
      targetPort: 4000

    - name: sujith
      port: 3001
      targetPort: 3000
