apiVersion: apps/v1
kind: Deployment
metadata:
  name: sujith-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mani
  template:
    metadata:
      labels:
        app: mani
    spec:
      containers:
        - name: sujith-cont
          image: manikanta1432/sujith-project-image:v1.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-svc:27017/sujitha